### PR TITLE
feat: all the things!

### LINKED ISSUE #2: Return default prediction when horoskopy are down
Time to time maintainers of horoskopy.cz do things like a failover location test. During this period `horoskopycli` usually does not work. It would be nice to return some kind of default prediction.

``` bash
$ horoskopycli vahy
2024/06/25 12:07:49 Could not find contant element
```

### PR DESCRIPTION
**Pull request by FUSAKLA**
/fixes #2

But there is more! :grimacing: 

 - adds linting
 - adds makefile
 - upgrades go to 1.22
 - adds linting to CI
 - adds developmnet docs
 - fixes some lint
 - and finally adds sorry-message if horoskopy.cz returns something else then 200

Signed-off-by: Martin Chodur <m.chodur@seznam.cz>

### CODE REVIEW

**Comment by FUSAKLA** [comment]
Hey @kozaktomas WE ARE LOOSING MONEY EVERY DAY BECAUSE OF NOT HAVING THIS MERGED!!!

**Comment by kozaktomas** [comment]
I am so sorry for the delay. Thank you @FUSAKLA for your contribution. It will definitely help all users! 

Let me promote you to the maintainer. 

A Million Thanks! :tada:

**Review by kozaktomas — APPROVED** [review]
LGTM

**Comment by kozaktomas** [comment]
Thanks again!

**Pull request merged**
